### ISSUE TITLE
Good Project - Preferred comm channel?

### ISSUE THREAD

**Issue by moose99** [HA6Bots/FESBSC-Development-GitHub#2]
This looks like a good effort, thanks for the collaboration invite.  Just curious, how did you find me?

What's the preferred method of communication?  Just using Issues or some other mailing list/chat/slack channel?

A couple quick notes:
-We could also add support for 2captcha (for users with 2captcha accounts).  I integrated this recently into my own Supreme bot.   (BTW, it seemed that Supreme could detect Selenium based bots and always declined my purchase with 'violation of terms' reason.)
-What's the reason for committing the pycache/pyc files?

Thanks,
-Moose99

**Comment by HA6Bots** [comment]
I found you because you starred the project :)

Right now I'm still trying to find a channel for all the contributors to communicate on, everyone has different preferences but I may create a discord channel. For now email/pm is fine.

Since selenium runs chrome driver as a 'automated browser for testing purposes' I'm not surprised that Supreme can detect selenium. I am currently looking into different libraries that could be used. Alternatively I may develop my own library that utilises screen imaging technology to read the website off chrome/ie/Firefox or any other browser without the browser ever knowing.

**Comment by mvabdi** [comment]
I was spooked on how you found me too lol.

anyway, @moose99 have you tried slowing down the bot or using a proxy?

Another thing that might be messing you up is the tohru cookie, which has something to do with JS or mouse movement

**Comment by mvabdi** [comment]
Also with 2captcha, I added that to my bot a while ago and gave up on it due to the long times taken to get my captcha back, and especially since Supreme only allows for captcha responses after the site has been updated. So you have very little time to get the response back. What I do to bypass captcha is just sign in to gmail, and I dont get a response most of the time

**Comment by HA6Bots** [comment]
Does the gmail method work even on selenium?

**Comment by danielyc** [comment]
Yes the gmail method works just fine.  

Mvg Daniël Abrahams
OSCP - Netsec Nederland

> Op 22 dec. 2017 om 04:09 heeft HA6Bots <notifications@github.com> het volgende geschreven:
> 
> Does the gmail method work even on selenium?
>

**Comment by moose99** [comment]
>have you tried slowing down the bot or using a proxy
I added a checkout delay of up to 10 seconds and also slowed down the form filling operations and it didn't help.  I haven't tried a proxy because I can get to the site just fine, only the purchase is declined (so my IP isn't banned or anything).  In fact, if the browser is launched via Selenium (or splinter) but I fill out the cart info manually and do captcha manually, it still declines with 'violation of terms' message.

> Supreme only allows for captcha responses after the site has been updated
Yes, I noticed this too, but I think the solution is to begin harvesting multiple captcha solutions in separate threads ahead of time, and then only use the ones that arrive AFTER the site is updated. Let me know if that isn't clear.

>Yes the gmail method works just fine
For me, I always log into my google account first and then solve some captchas manually from here:
https://www.google.com/recaptcha/api2/demo?invisible=true
BUT, Supreme still forces me to solve multiple captchas on drop day which takes way too long. ;-(

**Comment by HA6Bots** [comment]
Moose99, so does Supreme always deny your purchase with and without a bot? Which browsers do you use/is it an automated browser like chromedriver?

**Comment by HA6Bots** [comment]
I am going to clean up the code today as it is getting a bit messy.

**Comment by moose99** [comment]
>Moose99, so does Supreme always deny your purchase with and without a bot?

No, if I run my chrome browser manually, I can make a purchase.  But if I launch the browser using chromedriver via selenium, the purchase is always declined.  It seems they are detecting that case.  I tried different user agents and headers with selenium and various selenium chrome driver options like incognito or not, but haven't been able to make a purchase that way (even after using manual input after the selenium browser appears)

**Comment by HA6Bots** [comment]
Yes it appears that using these mainstream automated browser libraries like Selenium or Splinter allows for easy detection by Chrome/Supreme.  I am going to work on my own library for the project that allows for browser manipulation through screen imaging.
